gui:
  theme:
    activeBorderColor:
      - '#FFFFFF'
      - bold
    inactiveBorderColor:
      - '#8C8C8C'
    optionsTextColor:
      - '#FFFFFF'
      - bold
    selectedLineBgColor:
      - '#4D4D4D'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#8C8C8C'
    defaultFgColor:
      - '#FFFFFF'
    searchingActiveBorderColor:
      - '#f9e2af'
